language: python

python:
  - "3.6"
#  - "2.7"

script:
  - python scripts/lagDokumentasjon.py

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master

notifications:
  email: false
