proc format;
value $ICD10kap2016F
1="Kapittel I: Visse infeksjonssykdommer og parasittsykdommer"
2="Kapittel II: Svulster"
3="Kapittel III Sykdommer i blod og bloddannende organer og visse tilstander som angår immunsystemet"
4="Kapittel IV: Endokrine sykdommer, ernæringssykdommer og metabolske forstyrrelser"
5="Kapittel V: Psykiske lidelser og atferdsforstyrrelser"
6="Kapittel VI: Sykdommer i nervesystemet"
7="Kapittel VII: Sykdommer i øyet og øyets omgivelser"
9="Kapittel IX: Sykdommer i sirkulasjonssystemet"
10="Kapittel X: Sykdommer i åndedrettssystemet"
11="Kapittel XI: Sykdommer i fordøyelsessystemet"
12="Kapittel XII: Sykdommer i hud og underhud"
13="Kapittel XIII: Sykdommer i muskel-skjelettsystemet og bindevev"
14="Kapittel XIV: Sykdommer i urin- og kjønnsorganer"
15="Kapittel XV: Svangerskap, fødsel og barseltid"
16="Kapittel XVI: Visse tilstander som oppstår i perinatalperioden"
17="Kapittel XVII: Medfødte misdannelser, deformiteter og kromosomavvik"
18="Kapittel XVIII: Symptomer, tegn, unormale kliniske funn og laboratoriefunn, ikke klassifisert annet sted"
19="Kapittel XIX: Skader, forgiftninger og visse andre konsekvenser av ytre årsaker"
20="Kapittel XX: Ytre årsaker til sykdommer, skader og dødsfall"
21="Kapittel XXI: Faktorer som har betydning for helsetilstand og kontakt med helsetjenesten"
22="Kapittel XXII: Koder for spesielle formål (U00-U85)"
;
run;
