%macro Episode_of_care_hjelp;
options nomlogic nomprint;
%put ================================================================================;
%put Episode_of_care Makro - Opprettet 26.10.2016 av Frank Olsen;
%put Endret 26.10.2016 av Frank Olsen;
%put Datasettet må inneholde inndato utdato inntid og uttid;
%put Episode_of_care(dsn=,tidskrav=);
%put Parametre:;
%put 1. dsn: datasett man utfører analysen på;
%put 2. tidskrav: tidskrav i sekunder (28800 er 8 timer) for opphold med tidsdifferanse - må være ett tall;
%put Episode of care omfatter da:;
%put a. Dersom inndatotid på nytt opphold er før utdatotid på forrige opphold;
%put b. Dersom nytt opphold er innen x sekunder fra utdatotid på forrige opphold;
%put Makroen lager 9 nye variable:;
%put 1. Inndatotid;
%put 2. Utdatotid;
%put 3. diff: tidsdifferanse mellom inndatotid på dette oppholdet og utdatotid på forrige opphold;
%put 4. EOC_nr_pid: Nummererte EOC-opphold pr pid, dersom EOC består av flere opphold har disse samme nummer;
%put 5. EOC_Intern_nr: Nummerer oppholdene innenfor hver EOC for hver pid;
%put 6. EOC_Antall_i_EOC: Antall opphold i EOC;
%put 7. EOC_startdato: inndato på første opphold i EOC;
%put 8. EOC_sluttdato: utdato på siste opphold i EOC;
%put 9. EOC_liggetid: tidsdifferanse mellom inndatotid på det første oppholdet og utdatotid på det siste oppholdet i EOC;
%put ==================================================================================;
%mend Episode_of_care_hjelp;
