%macro Episode_of_care_hjelp;
options nomlogic nomprint;
%put ================================================================================;
%put Episode_of_care Makro - Opprettet 26.10.2016 av Frank Olsen;
%put Endret 26.10.2016 av Frank Olsen;
%put Endret 18.11.2016 av Frank Olsen - Lagt inn reinnleggelser;
%put Datasettet må inneholde inndato utdato inntid og uttid;
%put Episode_of_care(dsn=,tidskrav=28800, ReInn_tid=30,;
%put standard_where= and aktivitetskategori3=1 and hastegrad=1,;
%put tilleggs_where= , debug = 0);
%put Parametre:;
%put 1. dsn: datasett man utfører analysen på;
%put 2. tidskrav: tidskrav i sekunder (default 28800 er 8 timer) for opphold med tidsdifferanse - må være et tall;
%put 3. ReInn_tid: tidskrav for reinnleggelse i antall dager (default er 30 dager);
%put 4. standard_where: standard krav til reinnleggelse. Må starte med 'and' (and aktivitetskategori3=1 and hastegrad=1);
%put 5. tilleggs_where: ekstra krav til reinnleggelse. Må starte med 'and';
%put Episode of care omfatter da:;
%put a. Dersom inndatotid på nytt opphold er før utdatotid på forrige opphold;
%put b. Dersom nytt opphold er innen x sekunder fra utdatotid på forrige opphold;
%put Makroen lager 12 nye variable:;
%put 1. Inndatotid;
%put 2. Utdatotid;
%put 3. diff: tidsdifferanse mellom inndatotid på dette oppholdet og utdatotid på forrige opphold;
%put 4. EOC_nr_pid: Nummererte EOC-opphold pr pid, dersom EOC består av flere opphold har disse samme nummer;
%put 5. EoC_id: Unik ID for hver EoC (pid+EoC_nr_pid)
%put 6. EOC_Intern_nr: Nummerer oppholdene innenfor hver EOC for hver pid;
%put 7. EOC_Antall_i_EOC: Antall opphold i EOC;
%put 8. EOC_startdato: inndato på første opphold i EOC;
%put 9. EOC_sluttdato: utdato på siste opphold i EOC;
%put 10. EOC_liggetid: tidsdifferanse mellom inndatotid på det første oppholdet og utdatotid på det siste oppholdet i EOC;
%put 11. EoC_reinnleggelse: er 1 hvis dette er en reinnleggelse
%put 12. EoC_aktivitetskategori: 1 hvis ett oppholdene er døgn, 2 hvis ett av oppholdene er dag, 3 hvis ett av oppholdene er poli;
%put ==================================================================================;
%mend Episode_of_care_hjelp;
