%macro Label_m_info_hjelp;
options nomlogic nomprint;
%put ===========================================================================================;
%put Label_m_info Makro - Opprettet 30/11-15 av Frank Olsen;
%put For å legge på f.eks n=antall obs i label for boområder i søylediagram;
%put Label_m_info(inn_data=, Label_variabel=, Info_variabel=, Info_variabel_tekst=);
%put Parametre:;
%put 1. Inn_data: datasett man utfører analysen på;
%put 2. Label_variabel: Variabelen man ønsker å legge ekstra informasjon på;
%put 3. Info_variabel: Variabelen som har ekstra informasjonen man ønsker å legge på;
%put 4. Info_variabel_tekst: Forklaringsteksten for ekstra informasjonen;
%put ===========================================================================================;
%mend Label_m_info_hjelp;