%macro Unik_pasient_hjelp;
options nomlogic nomprint;
%put ===========================================================================================;
%put Unik_pasient Makro - Opprettet 1/12-15 av Frank Olsen;
%put For å finne unike pasienter, oppholdsnr og antall opphold pr pasient ut fra et "merke";
%put Unik_pasient(inn_data=, pr_aar=, sorter=, Pid=, Merke_variabel=);
%put Parametre:;
%put 1. Inn_data: datasett man utfører analysen på;
%put 2. pr_aar: settes=aar dersom man ønsker å finne unike pasienter pr år, ellers la stå tom;
%put 3. sorter: Andre variable det skal sorteres på, f.eks inndato og utdato;
%put 4. Pid: Settes=PID så lenge PID angir pasientid;
%put 5. Merke_variabel: Variabel det skal telles opp fra, må være merket med 1 for aktuelle;
%put -------------------------------------------------------------------------------------------;
%put Det lages tre nye variable i datasettet:;
%put 1. Unik_Pas_"Merke_variabel" --> lik 1 for unike pasienter;
%put 2. Nr_pr_pas_"Merke_variabel" --> Nummererer de aktuelle oppholdene pr pasient i rekkefølge;
%put 3. N_pr_pas_"Merke_variabel" --> Antall opphold totalt pr pasient, settes på alle opphold;
%put ===========================================================================================;
%mend Unik_pasient_hjelp;