name: Build and deploy documentation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: |
          python docs/extract_sas_documentation.py "makroer" "rateprogram" "tilrettelegging/npr/1_kontroll_foer_tilrette" "tilrettelegging/npr/2_tilrettelegging" "tilrettelegging/ssb" "include"
          rm docs/extract_sas_documentation.py # so it will not be part of deployment
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
